### ISSUE TITLE
can you give a  Arbitrarily long version ?

### ISSUE THREAD

**Issue by Jiuyong** [samboy/rg32hash#1]
i need a hash function ,and it can output Arbitrarily long hashcode . and then ,i find The RadioGatún Hash Function Family.
http://radiogatun.noekeon.org/
http://en.wikipedia.org/wiki/RadioGatún
but i don't know how make it in C# ~

**Comment by samboy** [comment]
A version of rg32hash with the ability to output an arbitrary long series of binary bits is here:

http://samiam.org/rg32/rg32-bin.c

This code is public domain.  I will close this ticket once I add that code to the Git tree.
- Sam

**Comment by samboy** [comment]
OK, rg32-bin.c added and closing this issue.
